List_ManualTest.obj : error LNK2019: 未解決の外部シンボル "public: __thiscall CList<struct TRecord>::CList<struct TRecord>(void)" (??0?$CList@UTRecord@@@@QAE@XZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::GetDataNumTest_TestGetDataNumWhenConst_Test::TestBody(void)" (?TestBody@GetDataNumTest_TestGetDataNumWhenConst_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2001: 外部シンボル ""public: __thiscall CList<struct TRecord>::CList<struct TRecord>(void)" (??0?$CList@UTRecord@@@@QAE@XZ)" は未解決です。
List_ManualTest.obj : error LNK2019: 未解決の外部シンボル "public: bool __thiscall CList<struct TRecord>::Insert(class CConstIterator<struct TRecord>,struct TRecord const &)" (?Insert@?$CList@UTRecord@@@@QAE_NV?$CConstIterator@UTRecord@@@@ABUTRecord@@@Z) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::ListManualTest_TestConstIteratorWhenConst_Test::TestBody(void)" (?TestBody@ListManualTest_TestConstIteratorWhenConst_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2001: 外部シンボル ""public: bool __thiscall CList<struct TRecord>::Insert(class CConstIterator<struct TRecord>,struct TRecord const &)" (?Insert@?$CList@UTRecord@@@@QAE_NV?$CConstIterator@UTRecord@@@@ABUTRecord@@@Z)" は未解決です。
List_ManualTest.obj : error LNK2019: 未解決の外部シンボル "public: class CIterator<struct TRecord> __thiscall CList<struct TRecord>::GetDummyFirst(void)" (?GetDummyFirst@?$CList@UTRecord@@@@QAE?AV?$CIterator@UTRecord@@@@XZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::ListManualTest_TestConstIteratorWhenConst_Test::TestBody(void)" (?TestBody@ListManualTest_TestConstIteratorWhenConst_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2001: 外部シンボル ""public: class CIterator<struct TRecord> __thiscall CList<struct TRecord>::GetDummyFirst(void)" (?GetDummyFirst@?$CList@UTRecord@@@@QAE?AV?$CIterator@UTRecord@@@@XZ)" は未解決です。
List_ManualTest.obj : error LNK2019: 未解決の外部シンボル "public: class CIterator<struct TRecord> __thiscall CList<struct TRecord>::GetDummyEnd(void)" (?GetDummyEnd@?$CList@UTRecord@@@@QAE?AV?$CIterator@UTRecord@@@@XZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::ListManualTest_TestConstEndIteratorWhenConst_Test::TestBody(void)" (?TestBody@ListManualTest_TestConstEndIteratorWhenConst_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2001: 外部シンボル ""public: class CIterator<struct TRecord> __thiscall CList<struct TRecord>::GetDummyEnd(void)" (?GetDummyEnd@?$CList@UTRecord@@@@QAE?AV?$CIterator@UTRecord@@@@XZ)" は未解決です。
List_ManualTest.obj : error LNK2019: 未解決の外部シンボル "public: int __thiscall CList<struct TRecord>::GetDataCnt(void)const " (?GetDataCnt@?$CList@UTRecord@@@@QBEHXZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::GetDataNumTest_TestGetDataNumWhenConst_Test::TestBody(void)" (?TestBody@GetDataNumTest_TestGetDataNumWhenConst_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2001: 外部シンボル ""public: int __thiscall CList<struct TRecord>::GetDataCnt(void)const " (?GetDataCnt@?$CList@UTRecord@@@@QBEHXZ)" は未解決です。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: bool __thiscall CList<struct TRecord>::Delete(class CConstIterator<struct TRecord>)" (?Delete@?$CList@UTRecord@@@@QAE_NV?$CConstIterator@UTRecord@@@@@Z) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::GetDataNumTest_TestGetDataCntDelete_Test::TestBody(void)" (?TestBody@GetDataNumTest_TestGetDataCntDelete_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: class CIterator<struct TRecord> __thiscall CList<struct TRecord>::GetFirstNode(void)" (?GetFirstNode@?$CList@UTRecord@@@@QAE?AV?$CIterator@UTRecord@@@@XZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::GetDataNumTest_TestGetDataCntDelete_Test::TestBody(void)" (?TestBody@GetDataNumTest_TestGetDataCntDelete_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: class CIterator<struct TRecord> __thiscall CList<struct TRecord>::GetEndNode(void)" (?GetEndNode@?$CList@UTRecord@@@@QAE?AV?$CIterator@UTRecord@@@@XZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::PushBackTest_TestDeleteEnd_Test::TestBody(void)" (?TestBody@PushBackTest_TestDeleteEnd_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: struct TNode<struct TRecord> * __thiscall CList<struct TRecord>::GetNode(int)const " (?GetNode@?$CList@UTRecord@@@@QBEPAU?$TNode@UTRecord@@@@H@Z) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::PushBackTest_TestPushFirstToSecond_Test::TestBody(void)" (?TestBody@PushBackTest_TestPushFirstToSecond_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: __thiscall CConstIterator<struct TRecord>::CConstIterator<struct TRecord>(struct TNode<struct TRecord> *)" (??0?$CConstIterator@UTRecord@@@@QAE@PAU?$TNode@UTRecord@@@@@Z) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::PushBackTest_TestPushMiddleConst_Test::TestBody(void)" (?TestBody@PushBackTest_TestPushMiddleConst_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: void __thiscall CConstIterator<struct TRecord>::GoPrevNode(void)" (?GoPrevNode@?$CConstIterator@UTRecord@@@@QAEXXZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::IteratorTest_TestEndIteratorForFirstWhenListEmpty_Test::TestBody(void)" (?TestBody@IteratorTest_TestEndIteratorForFirstWhenListEmpty_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: void __thiscall CConstIterator<struct TRecord>::GoNextNode(void)" (?GoNextNode@?$CConstIterator@UTRecord@@@@QAEXXZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::IteratorTest_TestFirstIteratorForEndWhenListEmpty_Test::TestBody(void)" (?TestBody@IteratorTest_TestFirstIteratorForEndWhenListEmpty_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: struct TNode<struct TRecord> * __thiscall CConstIterator<struct TRecord>::Getm_node(void)const " (?Getm_node@?$CConstIterator@UTRecord@@@@QBEPAU?$TNode@UTRecord@@@@XZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::PushBackTest_TestDeleteCenterConst_Test::TestBody(void)" (?TestBody@PushBackTest_TestDeleteCenterConst_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
List_Test.obj : error LNK2019: 未解決の外部シンボル "public: struct TNode<struct TRecord> * __thiscall CIterator<struct TRecord>::Getm_node(void)" (?Getm_node@?$CIterator@UTRecord@@@@QAEPAU?$TNode@UTRecord@@@@XZ) が関数 "private: virtual void __thiscall ex01_DataStructure::chapter2::PushBackTest_TestDeleteFirst_Test::TestBody(void)" (?TestBody@PushBackTest_TestDeleteFirst_Test@chapter2@ex01_DataStructure@@EAEXXZ) で参照されました。
C:\Users\ohs95038\Desktop\インターン\エンジニア課題\1_3_双方リストをテンプレート化する\Test\Debug\Test.exe : fatal error LNK1120: 14 件の未解決の外部参照
